package com.atrium.cliente;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "Servicio_WebDelegate", targetNamespace = "http://servicio.atrium.com/")
public interface ServicioWebDelegate {

	/**
	 * 
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "saludo", targetNamespace = "http://servicio.atrium.com/", className = "com.atrium.cliente.Saludo")
	@ResponseWrapper(localName = "saludoResponse", targetNamespace = "http://servicio.atrium.com/", className = "com.atrium.cliente.SaludoResponse")
	public String saludo();

	/**
	 * 
	 * @return returns javax.xml.datatype.XMLGregorianCalendar
	 */
	@WebMethod(operationName = "fecha_Actual")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "fecha_Actual", targetNamespace = "http://servicio.atrium.com/", className = "com.atrium.cliente.FechaActual")
	@ResponseWrapper(localName = "fecha_ActualResponse", targetNamespace = "http://servicio.atrium.com/", className = "com.atrium.cliente.FechaActualResponse")
	public XMLGregorianCalendar fechaActual();

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.Integer
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "sumar", targetNamespace = "http://servicio.atrium.com/", className = "com.atrium.cliente.Sumar")
	@ResponseWrapper(localName = "sumarResponse", targetNamespace = "http://servicio.atrium.com/", className = "com.atrium.cliente.SumarResponse")
	public Integer sumar(
			@WebParam(name = "arg0", targetNamespace = "") Integer arg0,
			@WebParam(name = "arg1", targetNamespace = "") Integer arg1);

}
