package com.atrium.cliente;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * Servicio_WebService service = new Servicio_WebService();
 * ServicioWebDelegate portType = service.getServicioWebPort();
 * portType.saludo(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "Servicio_WebService", targetNamespace = "http://servicio.atrium.com/", wsdlLocation = "http://localhost:8080/servicios-ws-inicial/Servicio_WebPort?WSDL")
public class ServicioWebService extends Service {

	private final static URL SERVICIOWEBSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.atrium.cliente.ServicioWebService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.atrium.cliente.ServicioWebService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://localhost:8080/servicios-ws-inicial/Servicio_WebPort?WSDL");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/servicios-ws-inicial/Servicio_WebPort?WSDL', retrying as a local file");
			logger.warning(e.getMessage());
		}
		SERVICIOWEBSERVICE_WSDL_LOCATION = url;
	}

	public ServicioWebService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public ServicioWebService() {
		super(SERVICIOWEBSERVICE_WSDL_LOCATION, new QName(
				"http://servicio.atrium.com/", "Servicio_WebService"));
	}

	/**
	 * 
	 * @return returns ServicioWebDelegate
	 */
	@WebEndpoint(name = "Servicio_WebPort")
	public ServicioWebDelegate getServicioWebPort() {
		return super.getPort(new QName("http://servicio.atrium.com/",
				"Servicio_WebPort"), ServicioWebDelegate.class);
	}

}
